name: first_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  data_connection_checker_nulls: ^0.0.2
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.13
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  connectivity_for_web: ^0.4.0+1
  bloc: ^8.0.3

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1

flutter:

  
  uses-material-design: true

  